export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const SET_TO_DO_DONE = 'SET_TO_DO_DONE';
export const DELETE_TASK = 'DELETE_TASK';
export const START_EDITING = 'START_EDITING';
export const FINISH_EDITING = 'FINISH_EDITING';
export const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';


